#spring配置
spring:
  datasource:
    url: jdbc:p6spy:mysql://127.0.0.1:3306/lanjerry?useUnicode=yes&characterEncoding=UTF8&useSSL=false&serverTimezone=CTT&allowMultiQueries=true
    username: root
    password: 123456
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
    hikari:
      # 最小空闲连接数量
      minimum-idle: 5
      # 连接池最大连接数，默认是10
      maximum-pool-size: 15
      # 此属性控制从池返回的连接的默认自动提交行为,默认值：true
      auto-commit: true
      # 一个连接idle状态的最大时长（毫秒），超时则被释放（retired），缺省:10分钟
      idle-timeout: 600000
      # 此属性控制池中连接的最长生命周期，值0表示无限生命周期，默认1800000即30分钟
      max-lifetime: 1800000
      # 数据库连接超时时间,默认30秒，即30000
      connection-timeout: 60000
  aop:
    proxy-target-class: true
    auto: true