# 启用配置文件 prod->生产环境  dev->开发环境  本地启动时切换到开发环境
# spring配置
spring:
  profiles:
    active: dev
  #文件上传的大小限制
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 30MB

# server配置
server:
  compression:
    enabled: true
    mime-types: application/json,application/xml,text/html,text/xml,text/plain
    min-response-size: 1024
  port: 1000

# mybatis-plus配置
mybatis-plus:
  global-config:
    db-config:
      id-type: auto
      logic-delete-value: 1
      logic-not-delete-value: 0
    banner: false
  mapper-locations: classpath:/mapper/*/*Mapper.xml
  type-enums-package: org.lanjerry.common.core.enums
  type-aliases-package: org.lanjerry.common.core.entity

# 代码生成
gen:
  # 作者
  author: lanjerry
  # 默认生成包路径 system 需改成自己的模块名称 如 system monitor tool
  packageName: org.lanjerry.admin
  # 自动去除表前缀，默认是true
  autoRemovePre: false

# 演示模式配置
demo:
  enable: false