#spring配置
spring:
  datasource:
    url: jdbc:p6spy:mysql://${MYSQL_HOST:127.0.0.1}:${MYSQL_PORT:3306}/${MYSQL_DATA_BASE:lanjerry}?useUnicode=yes&characterEncoding=UTF8&useSSL=false&serverTimezone=CTT&allowMultiQueries=true
    username: ${MYSQL_USER:root}
    password: ${MYSQL_PASSWORD:123456}
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
    hikari:
      # 最小空闲连接数量
      minimum-idle: 5
      # 连接池最大连接数，默认是10
      maximum-pool-size: 15
      # 此属性控制从池返回的连接的默认自动提交行为,默认值：true
      auto-commit: true
      # 一个连接idle状态的最大时长（毫秒），超时则被释放（retired），缺省:10分钟
      idle-timeout: 600000
      # 此属性控制池中连接的最长生命周期，值0表示无限生命周期，默认1800000即30分钟
      max-lifetime: 1800000
      # 数据库连接超时时间,默认30秒，即30000
      connection-timeout: 60000
  aop:
    proxy-target-class: true
    auto: true
  redis:
    host: ${REDIS_HOST:127.0.0.1}
    port: ${REDIS_PORT:6379}
    password: ${REDIS_PASSWORD:123456}
    timeout: 5000ms
    lettuce:
      pool:
        min-idle: 1
        max-active: 10
        max-wait: -1ms
        max-idle: 10

# 演示模式配置
demo:
  enable: false

# swagger配置
knife4j:
  # 开启生产环境,屏蔽Swagger所有资源接口
  production: false
  ## 开启Swagger的Basic认证功能,默认是false
  basic:
    enable: true
    username: admin
    password: 123456