version: '3.3'
services:
  admin:
    image: lanjerry-admin:v1.0
    container_name: admin
    ports:
      - "1000:1000"
    networks:
      - lanjerry-network
    restart: always
    links:
      - mysql
      - redis
    depends_on:
      - mysql
      - redis
    environment:
      MYSQL_HOST: mysql
      MYSQL_PORT: 3306
      MYSQL_DATA_BASE: lanjerry
      MYSQL_USER: root
      MYSQL_PASSWORD: 123456
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_PASSWORD: 123456
      JAVA_OPTS: -Xms256m -Xmx256m
    deploy:
      resources:
        limits:
          memory: 500M
        reservations:
          memory: 500M
    volumes:
      - /opt/lanjerry/logs:/opt/lanjerry/logs
  mysql:
    image: mysql:8.0.18
    ports:
      - "3306:3306"
    networks:
      - lanjerry-network
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123456
  redis:
    image: redis
    ports:
      - "6379:6379"
    networks:
      - lanjerry-network
    container_name: redis
    restart: always
    command: [ "redis-server", "--appendonly", "yes", "--requirepass","123456" ]
networks:
  lanjerry-network:
    external: true