pipeline{
    agent any
     parameters {
        booleanParam(name: 'package', defaultValue: true, description: '打包项目')
        booleanParam(name: 'push', defaultValue: false, description: '推送镜像')
        string(name: 'version', defaultValue: 'v1.0', description: '推送镜像版本')
    }
    tools {
        maven 'maven3.6.3'
    }
    stages{
        stage("package"){
            when {
                expression { return params.package } 
            }
            steps{
                sh 'mvn clean package -Dmaven.skip.tests=true'
            }
           
        }
        stage("build images"){
            steps{
                sh 'docker build -t lanjerry-admin-api lanjerry-admin/.'
                sh 'docker tag lanjerry-admin-api lanjerry-admin-api:${version}'
            }
        }
        stage("run"){
            steps{
                sh 'docker-compose -f lanjerry-admin/docker-compose-admin.yml up -d'
            }
        }
        stage("push"){
            when {
                expression { return params.push } 
            }
             steps{
                sh 'docker tag lanjerry-admin-api:${version} registry.cn-shenzhen.aliyuncs.com/lanjerry/lanjerry-admin-api:${version}'
                sh 'docker push registry.cn-shenzhen.aliyuncs.com/lanjerry/lanjerry-admin-api:${version}'
            }
        }
    }
}